# Generated by Django 5.1.7 on 2025-05-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("platform", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=100)),
                ("developer", models.CharField(max_length=100)),
                ("publisher", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
            ],
            options={
                "ordering": ["-average_rating"],
            },
        ),
    ]
