# Generated by Django 5.1.7 on 2025-05-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamerank", "0003_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="xml_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Identificador original según el XML",
                null=True,
                unique=True,
            ),
        ),
    ]
