# Generated by Django 5.1.7 on 2025-05-11 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamerank", "0004_game_xml_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followed_games", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
