# Generated by Django 5.1.7 on 2025-05-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamerank", "0005_game_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="xml_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
