# Generated by Django 5.1.7 on 2025-05-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamerank", "0006_game_thumbnail_alter_game_title_alter_game_xml_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="rating",
        ),
    ]
